### ISSUE TITLE
a few thoughts

### ISSUE THREAD

**Issue by ChristianKuehnel** [ReneNulschDE/ha_cc_mbwebapppy#1]
Hi @ReneNulschDE ,

great work with the HA integration!

Some things I notices when I started using it today:
- I would like to be able to control the auxiliary heating of my car from HA. If you haven't been working on this yet, I'm willing to look into implementing this.
- It would be great to have some common prefix in the name of all vehicle-sensors, so that they are easier to find in the list of sensors. Something like `sensor.<mycar>_distance_since_reset`. This would also (later) allow the usage of multiple cars.
- I would also like to give the device_tracker a name rather than using the VIN.
- I would prefer the door lock status to be some text (locked, unlocked) instead of the numbers 0-2.

Thank you for creating this component!

Best,
Christian

**Comment by ReneNulschDE** [comment]
Hi Christian,

1. This is not possible with this version of the API. The underlying API has no access to this functionality. Please follow this forum thread (https://community.home-assistant.io/t/mercedes-me-component/41911/147). Maybe we see something new in the next couple of weeks. In case you are interested in supporting the developement, let me know in the forum and we can discuss offline.
2. This is implemented already. Each sensor has the licenseplate as a prefix. In my environment its running fine with two cars.
3. The Device Tracker has the license plate as friendly name by default. You could overwrite this with standard HA customizations
4. You mean the windows here? Thats true, could be handled better. Please check if you could use a template sensor and change your setup to your needs.

Thanks
Rene
